//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OBS.rc
//
#define IDC_DEFAULTS                    3
#define IDOK2                           3
#define IDC_APPLY                       4
#define IDC_OPTIMIZE                    5
#define IDD_SETTINGS                    101
#define IDI_ICON1                       109
#define IDI_SOUND_MIC                   110
#define IDI_SOUND_MIC_MUTED             111
#define IDI_SOUND_DESKTOP               112
#define IDI_SOUND_DESKTOP_MUTED         113
#define IDD_SETTINGS_PUBLISH            114
#define IDD_SETTINGS_ENCODING           115
#define IDD_SETTINGS_VIDEO              116
#define IDD_SETTINGS_GENERAL            117
#define IDD_SETTINGS_AUDIO              119
#define IDD_ENTERNAME                   122
#define IDD_CONFIGUREDESKTOPSOURCE      123
#define IDD_CONFIGUREBITMAP             124
#define IDD_CONFIGUREBITMAPSOURCE       124
#define IDR_ACCELERATOR1                125
#define IDD_GLOBAL_SOURCES              126
#define IDD_PLUGINS                     129
#define IDD_SCENEHOTKEY                 130
#define IDD_DIALOG1                     131
#define IDD_RECONNECTING                131
#define IDD_SETTINGS_ADVANCED           132
#define IDR_MAINMENU                    133
#define IDD_CONFIGURETRANSITIONSOURCE   135
#define IDD_BUILDINGMP4                 137
#define IDD_CONFIGURETEXTSOURCE         139
#define IDD_ENDINGDELAY                 140
#define IDI_ICON2                       142
#define IDD_CONFIGUREWINDOWCAPTURE      143
#define IDD_MONITORCAPTURE              144
#define IDD_CONFIGUREMONITORCAPTURE     144
#define IDD_STATS                       145
#define IDD_LOGUPLOADED                 147
#define IDD_SETTINGS_HOTKEYS            149
#define IDD_SETTINGS_QSV                150
#define IDD_GLOBAL_SOURCES_IMPORT       151
#define IDC_SETTINGSLIST                1006
#define IDC_SUBDIALOG                   1007
#define IDC_MODE                        1008
#define IDC_USERNAME                    1009
#define IDC_STREAMKEY                   1011
#define IDC_PLAYPATH                    1011
#define IDC_CHANNELNAME                 1012
#define IDC_QUALITY                     1012
#define IDC_URL                         1012
#define IDC_SERVER                      1013
#define IDC_PRESET                      1013
#define IDC_SERVERLIST                  1013
#define IDC_SERVICE                     1014
#define IDC_DOWNSCALE                   1014
#define IDC_BINDIP                      1014
#define IDC_MAXBITRATE                  1015
#define IDC_COLORPICKER                 1015
#define IDC_DOWNSCALE2                  1015
#define IDC_FILTER                      1015
#define IDC_PRESET2                     1015
#define IDC_X264PROFILE                 1015
#define IDC_BUFFERSIZE                  1016
#define IDC_FILTER2                     1016
#define IDC_DEVICE                      1016
#define IDC_AUDIOCODEC                  1017
#define IDC_USECOLORKEY                 1017
#define IDC_AUDIOFORMAT                 1018
#define IDC_AUDIOBITRATE                1019
#define IDC_MONITOR                     1019
#define IDC_BASETHRESHOLD_EDIT          1020
#define IDC_KEYFRAMEINTERVAL_EDIT       1020
#define IDC_VIDEOCODEC                  1020
#define IDC_AUDIOCHANNEL                1021
#define IDC_BASETHRESHOLD               1021
#define IDC_BLEND_EDIT                  1022
#define IDC_BLEND                       1023
#define IDC_LANGUAGE                    1028
#define IDC_INFO                        1029
#define IDC_FPS                         1030
#define IDC_PROFILE                     1030
#define IDC_INFO2                       1030
#define IDC_WARNINGS                    1030
#define IDC_QSV_CONFIG_WARNING          1030
#define IDC_FPS_EDIT                    1031
#define IDC_QSV_WINVER_WARNING          1031
#define IDC_SIZEX                       1033
#define IDC_SIZEY                       1034
#define IDC_GAMMA                       1035
#define IDC_ASPECT                      1035
#define IDC_USECUSTOM                   1036
#define IDC_POINTFILTERING              1036
#define IDC_USEMONITOR                  1037
#define IDC_DISABLEAERO                 1038
#define IDC_DISABLEMIC                  1040
#define IDC_CHECK1                      1041
#define IDC_RESETSIZE                   1041
#define IDC_CAPTUREMOUSE                1041
#define IDC_BUFFERSENDS                 1041
#define IDC_AUTORECONNECT               1041
#define IDC_PUSHTOTALK                  1041
#define IDC_USEVIDEOENCODERSETTINGS     1041
#define IDC_FADEINONLY                  1041
#define IDC_OPACITY                     1041
#define IDC_USETEXTEXTENTS              1041
#define IDC_CUSTOMBUFFER                1041
#define IDC_NOTIFICATIONICON            1041
#define IDC_SERVEREDIT                  1042
#define IDC_USESENDBUFFER               1042
#define IDC_FORCEMONO                   1042
#define IDC_SCROLLSPEED                 1042
#define IDC_OPACITY2                    1042
#define IDC_DISABLEFADING               1042
#define IDC_CHANNELNAME_STATIC          1043
#define IDC_EXTENTWIDTH_EDIT            1043
#define IDC_URL_STATIC                  1043
#define IDC_FORCEMONO2                  1043
#define IDC_USEMICTIMESTAMP             1043
#define IDC_USEMICTIME                  1043
#define IDC_USEMICQPC                   1043
#define IDC_FADEINONLY3                 1043
#define IDC_RANDOMIZE                   1043
#define IDC_PLAYPATH_STATIC             1044
#define IDC_SCROLLSPEED3                1044
#define IDC_EXTENTHEIGHT_EDIT           1044
#define IDC_USERNAME_STATIC             1045
#define IDC_SAVETOFILE                  1045
#define IDC_SERVER_STATIC               1046
#define IDC_SERVICE_STATIC              1047
#define IDC_NAME                        1048
#define IDC_KEEPRECORDING               1048
#define IDC_BITMAP                      1049
#define IDC_BROWSE                      1050
#define IDC_REPLAYBUFFERBROWSE          1051
#define IDC_MICDEVICES                  1052
#define IDC_BROWSEUSERSERVICES          1052
#define IDC_SOURCES                     1053
#define IDC_ADD                         1054
#define IDC_REMOVE                      1055
#define IDC_PLUGINS                     1055
#define IDC_MOVEUP                      1056
#define IDC_REPLACE                     1056
#define IDC_ADD2                        1056
#define IDC_MOVEDOWN                    1057
#define IDC_DESCRIPTION                 1057
#define IDC_MOVEUPWARD                  1057
#define IDC_REMOVE2                     1057
#define IDC_MOVETOTOP                   1058
#define IDC_MOVEDOWNWARD                1058
#define IDC_MOVETOBOTTOM                1059
#define IDC_RENAME                      1060
#define IDC_MONITORCAPTURE              1061
#define IDC_RENAME2                     1061
#define IDC_REGIONCAPTURE               1062
#define IDC_CONFIG                      1063
#define IDC_POSX                        1063
#define IDC_POSY                        1064
#define IDC_WINDOWCAPTURE               1065
#define IDC_WINDOW                      1066
#define IDC_OUTERWINDOW                 1067
#define IDC_REFRESH                     1068
#define IDC_INNERWINDOW                 1069
#define IDC_SELECTREGION                1071
#define IDC_HOTKEY1                     1073
#define IDC_HOTKEY                      1073
#define IDC_PUSHTOTALKHOTKEY            1073
#define IDC_CLEAR                       1074
#define IDC_MUTEMICHOTKEY               1074
#define IDC_MUTEDESKTOPHOTKEY           1075
#define IDC_ADDNEW                      1077
#define IDC_EDIT1                       1078
#define IDC_AUTORECONNECT_TIMEOUT_EDIT  1078
#define IDC_VIDEOENCODERSETTINGS        1078
#define IDC_TRANSITIONTIME              1078
#define IDC_OPACITY_EDIT                1078
#define IDC_MICBOOST_EDIT               1078
#define IDC_TEXT                        1078
#define IDC_SPIN1                       1079
#define IDC_AUTORECONNECT_TIMEOUT       1079
#define IDC_TRANSITIONTIME_EDIT         1079
#define IDC_MICBOOST                    1079
#define IDC_TEXTSIZE                    1079
#define IDC_AUDIOTIMEADJUST             1079
#define IDC_AUTORECONNECT_TIMEOUT_STATIC 1080
#define IDC_TEXTOPACITY_EDIT            1080
#define IDC_PTTDELAY_EDIT               1080
#define IDC_KEYFRAMEINTERVAL            1080
#define IDC_RECONNECTING                1081
#define IDC_SAVEPATH                    1081
#define IDC_SCROLLSPEED_EDIT            1081
#define IDC_PTTDELAY                    1081
#define IDC_QSVVIDEOENCODERSETTINGS     1081
#define IDC_SAVEPATH_STATIC             1082
#define IDC_EXTENTWIDTH                 1082
#define IDC_MICBOOST_EDIT2              1082
#define IDC_MICTIMEOFFSET_EDIT          1082
#define IDC_EXTENTHEIGHT                1083
#define IDC_DELAY_EDIT                  1083
#define IDC_MICTIMEOFFSET               1083
#define IDC_DELAY                       1084
#define IDC_OUTLINETHICKNESS_EDIT       1084
#define IDC_DESKTOPBOOST_EDIT           1084
#define IDC_BACKGROUNDOPACITY_EDIT      1085
#define IDC_MICBOOST2                   1085
#define IDC_DESKTOPBOOST                1085
#define IDC_REPLAYBUFFERLENGTH_EDIT     1085
#define IDC_USESYNCFIX                  1086
#define IDC_REPLAYBUFFERLENGTH          1086
#define IDC_REPLAYBUFFERSAVEPATH_STATIC 1087
#define IDC_CLEARPUSHTOTALK             1088
#define IDC_REPLAYBUFFERSAVEPATH        1088
#define IDC_CLEARMUTEMIC                1089
#define IDC_SENDBUFFERSIZE              1089
#define IDC_CLEARMUTEDESKTOP            1090
#define IDC_LIST1                       1090
#define IDC_BITMAPS                     1090
#define IDC_CLEARPUSHTOTALK2            1091
#define IDC_STOPSTREAMHOTKEY            1093
#define IDC_CLEARHOTKEY                 1094
#define IDC_STOPSTREAMHOTKEY_STATIC     1095
#define IDC_STARTSTREAMHOTKEY_STATIC    1096
#define IDC_STARTSTREAMHOTKEY           1097
#define IDC_CLEARHOTKEY_STARTSTREAM     1098
#define IDC_CHECK2                      1099
#define IDC_USED3DCOMPATIBILITY         1099
#define IDC_DISABLED3DCOMPATIBILITY     1099
#define IDC_USEMULTITHREADEDOPTIMIZATIONS 1099
#define IDC_CAPTURELAYERED              1099
#define IDC_USEOUTLINE                  1099
#define IDC_LOWLATENCYMODE              1099
#define IDC_MINIZENOTIFICATION          1099
#define IDC_CONNECTEDONLY               1099
#define IDC_TIMER1                      1100
#define IDC_CAPTURERAM                  1100
#define IDC_COMPATIBILITYMODE           1100
#define IDC_USEMULTITHREADEDOPTIMIZATIONS2 1100
#define IDC_DISABLEPREVIEWENCODING      1100
#define IDC_PROGRESS1                   1101
#define IDC_ALLOWEXTRAHOTKEYMODIFIERS   1101
#define IDC_ALLOWOTHERHOTKEYMODIFIERS   1101
#define IDC_COLOR                       1104
#define IDC_OUTLINECOLOR                1105
#define IDC_COLORKEY                    1105
#define IDC_KEYCOLOR                    1105
#define IDC_USETEXT                     1106
#define IDC_USEVIDEOSYNC                1106
#define IDC_SYNCTOVIDEOTIME             1106
#define IDC_USEFILE                     1107
#define IDC_FILE                        1108
#define IDC_BACKGROUNDCOLOR             1109
#define IDC_FONT                        1112
#define IDC_TEXTSIZE_EDIT               1115
#define IDC_SELECTFONT                  1116
#define IDC_TEXTOPACITY                 1118
#define IDC_WRAP                        1119
#define IDC_TEXTOPACITY2                1120
#define IDC_OUTLINETHICKNESS            1120
#define IDC_EXAMPLE                     1121
#define IDC_TEXTOPACITY3                1121
#define IDC_BACKGROUNDOPACITY           1121
#define IDC_VERTICALSCRIPT              1122
#define IDC_UNDERLINE                   1123
#define IDC_ALIGN                       1124
#define IDC_SELECT                      1125
#define IDC_BOLD                        1126
#define IDC_DELAY_STATIC                1126
#define IDC_ITALIC                      1127
#define IDC_TIMELEFT                    1127
#define IDC_REPLAYBUFFERLENGTH_STATIC   1127
#define IDC_UNLOCKHIGHFPS               1128
#define IDC_ENCODEFULLRANGE             1129
#define IDC_CANCEL                      1130
#define IDC_UNLOCKHIGHFPS2              1130
#define IDC_USEQSV                      1130
#define IDC_QSVUSEVIDEOENCODERSETTINGS  1131
#define IDC_PRIORITY                    1132
#define IDC_USECBR                      1133
#define IDC_PADCBR                      1134
#define IDC_QSVLA                       1135
#define IDC_NVENCPRESET                 1139
#define IDC_DISABLECTSADJUST            1140
#define IDC_USECFR                      1141
#define IDC_PLAYBACKDEVICES             1142
#define IDC_AUDIOTIMEADJUST_EDIT        1144
#define IDC_LATENCYMETHOD               1145
#define IDC_DISABLETCPOPTIMIZATIONS     1146
#define IDC_LATENCYTUNE                 1147
#define IDC_SETSTREAMSIZE               1148
#define IDC_GAMMAVAL                    1151
#define IDC_SCENEBUFFERTIME_EDIT        1152
#define IDC_SCENEBUFFERTIME             1153
#define IDC_OUTLINEOPACITY_EDIT         1154
#define IDC_OUTLINEOPACITY              1155
#define IDC_PUSHTOTALKHOTKEY2           1156
#define IDC_WARNING                     1159
#define IDC_MICSYNCFIX                  1160
#define IDC_CHECK3                      1161
#define IDC_SCROLLMODE                  1161
#define IDC_ENABLEPROJECTORCURSOR       1161
#define IDC_TOTALFRAMES                 1163
#define IDC_DROPPEDFRAMES               1164
#define IDC_LATEFRAMES                  1165
#define IDC_SKIPPEDFRAMES               1166
#define IDC_BYTESTRANSFERRED            1167
#define IDC_TOTALFRAMES2                1168
#define IDC_USENVENC                    1169
#define IDC_BUTTON1                     1169
#define IDC_RESETMIC                    1169
#define IDC_COPY                        1169
#define IDC_STARTRECORDINGHOTKEY_STATIC 1170
#define IDC_COPIED                      1170
#define IDC_ANALYZE                     1171
#define IDC_NVENCPRESET_LABEL           1171
#define IDC_STOPRECORDINGHOTKEY_STATIC  1171
#define IDC_STARTRECORDINGHOTKEY        1172
#define IDC_QSVPRESET_LABEL             1172
#define IDC_QSVPRESET                   1173
#define IDC_STOPRECORDINGHOTKEY         1173
#define IDC_CLEARHOTKEY_STARTRECORDING  1174
#define IDC_SHOWLOGWINDOWONLAUNCH       1174
#define IDC_CLEARHOTKEY_STOPRECORDING   1175
#define IDC_ENCODERX264                 1175
#define IDC_ENCODERQSV                  1176
#define IDC_X264PRESET_LABEL            1176
#define IDC_SAVEREPLAYBUFFERHOTKEY_STATIC 1176
#define IDC_ENCODERNVENC                1177
#define IDC_SAVEREPLAYBUFFERHOTKEY      1177
#define IDC_SCENECOLLECTION             1178
#define IDC_CLEARHOTKEY_SAVEREPLAYBUFFER 1178
#define IDC_FILEOUTPUTMODE              1178
#define IDC_FILEOUTPUTNORMAL            1179
#define IDC_STARTREPLAYBUFFERHOTKEY_STATIC 1179
#define IDC_FILEOUTPUTREPLAYBUFFER      1180
#define IDC_STARTREPLAYBUFFERHOTKEY     1180
#define IDC_REPLAYBUFFERMEMORY_STATIC   1181
#define IDC_CLEARHOTKEY_STARTREPLAYBUFFER 1181
#define IDC_REPLAYBUFFERMEMORY          1182
#define IDC_STOPREPLAYBUFFERHOTKEY_STATIC 1182
#define IDC_QSVCBR                      1183
#define IDC_STOPREPLAYBUFFERHOTKEY      1183
#define IDC_QSVVBR                      1184
#define IDC_CLEARHOTKEY_STOPREPLAYBUFFER 1184
#define IDC_QSVAVBR                     1185
#define IDC_RECORDFROMREPLAYBUFFERHOTKEY_STATIC 1185
#define IDC_TARGETKBPS                  1186
#define IDC_RECORDFROMREPLAYBUFFERHOTKEY 1186
#define IDC_QSVCQP                      1187
#define IDC_CLEARHOTKEY_RECORDFROMREPLAYBUFFER 1187
#define IDC_QSVICQ                      1188
#define IDC_QSVLAICQ                    1189
#define IDC_QSVVCM                      1190
#define IDC_QSVMAXKBPS                  1191
#define IDC_MAXKBPS                     1191
#define IDC_ACCURACY_EDIT               1193
#define IDC_ACCURACY                    1194
#define IDC_CONVERGENCE_EDIT            1195
#define IDC_CONVERGENCE                 1196
#define IDC_QPI_EDIT                    1197
#define IDC_QPI                         1198
#define IDC_QPP_EDIT                    1199
#define IDC_QPP                         1200
#define IDC_QPB_EDIT                    1201
#define IDC_QPB                         1202
#define IDC_LADEPTH_EDIT                1203
#define IDC_LADEPTH                     1204
#define IDC_ICQQUALITY_EDIT             1205
#define IDC_ICQQUALITY                  1206
#define IDC_USECUSTOMPARAMS             1207
#define IDC_USEGLOBALBITRATE            1208
#define IDC_USEGLOBALBUFFERSIZE         1209
#define IDC_TSRCOPACITY_EDIT            1209
#define IDC_IMPORT                      1210
#define IDC_TSRCOPACITY                 1210
#define IDA_SOURCE_MOVEUP               40018
#define IDA_SOURCE_MOVEDOWN             40019
#define IDA_SOURCE_MOVETOTOP            40020
#define IDA_SOURCE_MOVETOBOTTOM         40021
#define IDA_SOURCE_CENTER               40022
#define IDA_SOURCE_RESETSIZE            40023
#define IDA_SOURCE_DELETE               40024
#define IDA_SOURCE_FITTOSCREEN          40026
#define ID_MAINMENU_MAINMENU            40028
#define ID_MAINMENU_SETTINGS            40029
#define ID_SETTINGS_MAINMENU            40030
#define ID_SETTINGS_MAINMENU40031       40031
#define ID_MAINMENU_MAINMENU40032       40032
#define ID_MAINMENU_                    40033
#define ID_MAINMENU_MAINMENU40034       40034
#define ID_SETTINGS_OPENCONFIGFOLDER    40035
#define ID_SETTINGS_OPENLOGFOLDER       40036
#define ID_HELP_OPENHELP                40037
#define ID_HELP_ABOUT                   40038
#define ID_FILE_EXIT                    40039
#define ID_SETTINGS_SETTINGS            40041
#define ID_MAINMENU_MAINMENU40042       40042
#define ID_HELP_VISITWEBSITE            40043
#define ID_MAINMENU_MAINMENU40044       40044
#define ID_ALWAYSONTOP                  40045
#define ID_FULLSCREENMODE               40046
#define ID_MAINMENU                     40047
#define ID_MAINMENU_NOTHINGHERE         40048
#define ID_MAINMENU_MAINMENU40048       40049
#define ID_FILE_SAVE2                   40050
#define IDA_SOURCE_LEFT_CANVAS          40051
#define ID_MAINMENU_NOTHINGHERE40051    40051
#define IDA_SOURCE_TOP_CANVAS           40052
#define ID_MAINMENU_MAINMENU40052       40052
#define IDA_SOURCE_RIGHT_CANVAS         40053
#define ID_MAINMENU_MAINMENU40053       40053
#define IDA_SOURCE_BOTTOM_CANVAS        40054
#define ID_SETTINGS_DISABLEPROJECTOR    40054
#define IDA_SOURCE_CENTER_VER           40055
#define IDA_SOURCE_CENTER_HOR           40056
#define IDA_SOURCE_RESETCROP            40057
#define ID_HELP_CHECK_FOR_UPDATES       40058
#define ID_HELP_UPLOAD_CURRENT_LOG      40060
#define ID_HELP_UPLOAD_LAST_LOG         40061
#define ID_MAINMENU_MAINMENU40062       40062
#define ID_HELP_ANALYZE_CURRENT_LOG     40063
#define ID_SETTINGS_SHOWCONSOLE         40066
#define ID_SHOWLOG                      40067
#define ID_RECORDINGSFOLDER             40068
#define ID_MAINMENU_NEW                 40069
#define ID_MAINMENU_CLONE               40070
#define ID_MAINMENU_REMOVE              40071
#define ID_SCENECOLLECTION_REMOVE       40072
#define ID_SCENECOLLECTION_CLONE        40073
#define ID_SCENECOLLECTION_NEW          40074
#define ID_MAINMENU_RENAME              40075
#define ID_SCENECOLLECTION_RENAME       40076
#define ID_MAINMENU_MAINMENU40077       40077
#define ID_MAINMENU_MAINMENU40078       40078
#define ID_SCENECOLLECTION_IMPORT       40079
#define ID_SCENECOLLECTION_EXPORT       40080
#define ID_SAVEDREPLAYBUFFERS           40081
#define ID_PROFILE_NEW                  40082
#define ID_PROFILE_RENAME               40083
#define ID_PROFILE_CLONE                40084
#define ID_PROFILE_REMOVE               40085
#define ID_PROFILE_IMPORT               40086
#define ID_PROFILE_EXPORT               40087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40088
#define _APS_NEXT_CONTROL_VALUE         1211
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
