//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OBS.rc
//
#define IDC_DEFAULTS                    3
#define IDC_APPLY                       4
#define IDD_SETTINGS                    101
#define IDI_ICON1                       109
#define IDI_SOUND_MIC                   110
#define IDI_SOUND_MIC_MUTED             111
#define IDI_SOUND_DESKTOP               112
#define IDI_SOUND_DESKTOP_MUTED         113
#define IDD_SETTINGS_PUBLISH            114
#define IDD_SETTINGS_ENCODING           115
#define IDD_SETTINGS_VIDEO              116
#define IDD_SETTINGS_GENERAL            117
#define IDD_SETTINGS_AUDIO              119
#define IDD_ENTERNAME                   122
#define IDD_CONFIGUREDESKTOPSOURCE      123
#define IDD_CONFIGUREBITMAP             124
#define IDD_CONFIGUREBITMAPSOURCE       124
#define IDR_ACCELERATOR1                125
#define IDD_GLOBAL_SOURCES              126
#define IDD_PLUGINS                     129
#define IDD_SCENEHOTKEY                 130
#define IDD_DIALOG1                     131
#define IDD_RECONNECTING                131
#define IDD_SETTINGS_ADVANCED           132
#define IDR_MAINMENU                    133
#define IDD_CONFIGURETRANSITIONSOURCE   135
#define IDD_BUILDINGMP4                 137
#define IDD_CONFIGURETEXTSOURCE         139
#define IDC_SETTINGSLIST                1006
#define IDC_SUBDIALOG                   1007
#define IDC_MODE                        1008
#define IDC_USERNAME                    1009
#define IDC_STREAMKEY                   1011
#define IDC_PLAYPATH                    1011
#define IDC_CHANNELNAME                 1012
#define IDC_QUALITY                     1012
#define IDC_SERVER                      1013
#define IDC_PRESET                      1013
#define IDC_SERVERLIST                  1013
#define IDC_SERVICE                     1014
#define IDC_DOWNSCALE                   1014
#define IDC_MAXBITRATE                  1015
#define IDC_COLORPICKER                 1015
#define IDC_BUFFERSIZE                  1016
#define IDC_AUDIOCODEC                  1017
#define IDC_USECOLORKEY                 1017
#define IDC_AUDIOFORMAT                 1018
#define IDC_AUDIOBITRATE                1019
#define IDC_MONITOR                     1019
#define IDC_BASETHRESHOLD_EDIT          1020
#define IDC_BASETHRESHOLD               1021
#define IDC_BLEND_EDIT                  1022
#define IDC_BLEND                       1023
#define IDC_LANGUAGE                    1028
#define IDC_INFO                        1029
#define IDC_FPS                         1030
#define IDC_PROFILE                     1030
#define IDC_FPS_EDIT                    1031
#define IDC_SIZEX                       1033
#define IDC_SIZEY                       1034
#define IDC_USECUSTOM                   1036
#define IDC_USEMONITOR                  1037
#define IDC_DISABLEAERO                 1038
#define IDC_DISABLEMIC                  1040
#define IDC_CHECK1                      1041
#define IDC_USEI444                     1041
#define IDC_RESETSIZE                   1041
#define IDC_CAPTUREMOUSE                1041
#define IDC_BUFFERSENDS                 1041
#define IDC_AUTORECONNECT               1041
#define IDC_PUSHTOTALK                  1041
#define IDC_USEVIDEOENCODERSETTINGS     1041
#define IDC_FADEINONLY                  1041
#define IDC_OPACITY                     1041
#define IDC_USETEXTEXTENTS              1041
#define IDC_SERVEREDIT                  1042
#define IDC_USESENDBUFFER               1042
#define IDC_FORCEMONO                   1042
#define IDC_SCROLLSPEED                 1042
#define IDC_CHANNELNAME_STATIC          1043
#define IDC_EXTENTWIDTH_EDIT            1043
#define IDC_PLAYPATH_STATIC             1044
#define IDC_SCROLLSPEED3                1044
#define IDC_EXTENTHEIGHT_EDIT           1044
#define IDC_USERNAME_STATIC             1045
#define IDC_SAVETOFILE                  1045
#define IDC_SERVER_STATIC               1046
#define IDC_SERVICE_STATIC              1047
#define IDC_NAME                        1048
#define IDC_BITMAP                      1049
#define IDC_BROWSE                      1050
#define IDC_MICDEVICES                  1052
#define IDC_SOURCES                     1053
#define IDC_ADD                         1054
#define IDC_REMOVE                      1055
#define IDC_PLUGINS                     1055
#define IDC_MOVEUP                      1056
#define IDC_REPLACE                     1056
#define IDC_MOVEDOWN                    1057
#define IDC_DESCRIPTION                 1057
#define IDC_MOVEUPWARD                  1057
#define IDC_MOVETOTOP                   1058
#define IDC_MOVEDOWNWARD                1058
#define IDC_MOVETOBOTTOM                1059
#define IDC_RENAME                      1060
#define IDC_MONITORCAPTURE              1061
#define IDC_REGIONCAPTURE               1062
#define IDC_CONFIG                      1063
#define IDC_POSX                        1063
#define IDC_POSY                        1064
#define IDC_WINDOWCAPTURE               1065
#define IDC_WINDOW                      1066
#define IDC_OUTERWINDOW                 1067
#define IDC_REFRESH                     1068
#define IDC_INNERWINDOW                 1069
#define IDC_SELECTREGION                1071
#define IDC_HOTKEY1                     1073
#define IDC_HOTKEY                      1073
#define IDC_PUSHTOTALKHOTKEY            1073
#define IDC_CLEAR                       1074
#define IDC_MUTEMICHOTKEY               1074
#define IDC_MUTEDESKTOPHOTKEY           1075
#define IDC_ADDNEW                      1077
#define IDC_EDIT1                       1078
#define IDC_AUTORECONNECT_TIMEOUT_EDIT  1078
#define IDC_VIDEOENCODERSETTINGS        1078
#define IDC_TRANSITIONTIME              1078
#define IDC_OPACITY_EDIT                1078
#define IDC_MICBOOST_EDIT               1078
#define IDC_TEXT                        1078
#define IDC_SPIN1                       1079
#define IDC_AUTORECONNECT_TIMEOUT       1079
#define IDC_TRANSITIONTIME_EDIT         1079
#define IDC_MICBOOST                    1079
#define IDC_TEXTSIZE                    1079
#define IDC_AUTORECONNECT_TIMEOUT_STATIC 1080
#define IDC_TEXTOPACITY_EDIT            1080
#define IDC_RECONNECTING                1081
#define IDC_SAVEPATH                    1081
#define IDC_SCROLLSPEED_EDIT            1081
#define IDC_SAVEPATH_STATIC             1082
#define IDC_EXTENTWIDTH                 1082
#define IDC_EXTENTHEIGHT                1083
#define IDC_USESYNCFIX                  1086
#define IDC_CLEARPUSHTOTALK             1088
#define IDC_CLEARMUTEMIC                1089
#define IDC_SENDBUFFERSIZE              1089
#define IDC_CLEARMUTEDESKTOP            1090
#define IDC_LIST1                       1090
#define IDC_BITMAPS                     1090
#define IDC_STOPSTREAMHOTKEY            1093
#define IDC_CLEARHOTKEY                 1094
#define IDC_STOPSTREAMHOTKEY_STATIC     1095
#define IDC_STARTSTREAMHOTKEY_STATIC    1096
#define IDC_STARTSTREAMHOTKEY           1097
#define IDC_CLEARHOTKEY_STARTSTREAM     1098
#define IDC_CHECK2                      1099
#define IDC_USED3DCOMPATIBILITY         1099
#define IDC_DISABLED3DCOMPATIBILITY     1099
#define IDC_USEMULTITHREADEDOPTIMIZATIONS 1099
#define IDC_TIMER1                      1100
#define IDC_PROGRESS1                   1101
#define IDC_DASHBOARDLINK_STATIC        1102
#define IDC_DASHBOARDLINK               1103
#define IDC_COLOR                       1104
#define IDC_USEHIGHQUALITYRESAMPLING    1105
#define IDC_USETEXT                     1106
#define IDC_USEFILE                     1107
#define IDC_FILE                        1108
#define IDC_FONT                        1112
#define IDC_TEXTSIZE_EDIT               1115
#define IDC_SELECTFONT                  1116
#define IDC_TEXTOPACITY                 1118
#define IDC_WRAP                        1119
#define IDC_EXAMPLE                     1121
#define IDC_VERTICALSCRIPT              1122
#define IDC_UNDERLINE                   1123
#define IDC_ALIGN                       1124
#define IDC_SELECT                      1125
#define IDC_BOLD                        1126
#define IDC_ITALIC                      1127
#define IDA_SOURCE_MOVEUP               40018
#define IDA_SOURCE_MOVEDOWN             40019
#define IDA_SOURCE_MOVETOTOP            40020
#define IDA_SOURCE_MOVETOBOTTOM         40021
#define IDA_SOURCE_CENTER               40022
#define IDA_SOURCE_RESETSIZE            40023
#define IDA_SOURCE_DELETE               40024
#define IDA_SOURCE_FITTOSCREEN          40026
#define ID_MAINMENU_MAINMENU            40028
#define ID_MAINMENU_SETTINGS            40029
#define ID_SETTINGS_MAINMENU            40030
#define ID_SETTINGS_MAINMENU40031       40031
#define ID_MAINMENU_MAINMENU40032       40032
#define ID_MAINMENU_                    40033
#define ID_MAINMENU_MAINMENU40034       40034
#define ID_SETTINGS_OPENCONFIGFOLDER    40035
#define ID_SETTINGS_OPENLOGFOLDER       40036
#define ID_HELP_CONTENTS                40037
#define ID_HELP_ABOUT                   40038
#define ID_FILE_EXIT                    40039
#define ID_SETTINGS_SETTINGS            40041
#define ID_MAINMENU_MAINMENU40042       40042
#define ID_HELP_VISITWEBSITE            40043

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         40044
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
